version: 2
jobs:
  build:
    working_directory: /WebApp.calendar.blog
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Build up
          command: |
            docker-compose up -d
      - deploy:
          name: Publish calendar image
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag odtcmilosradojicic/calendarapp $DOCKER_HUB_USER_ID/calendarapp:$CIRCLE_SHA1
            docker tag odtcmilosradojicic/calendarapp $DOCKER_HUB_USER_ID/calendarapp:latest
            docker push $DOCKER_HUB_USER_ID/calendarapp:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/calendarapp:latest